---
title: "Report on the use of prescribed fire on bird communities in Canada's National Parks"
format:
  html:
    grid:
      margin-width: 300px
navbar: right
theme: cosmo
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: 
  - name: "Alex MacPhail"
    affiliation: "Biodiversity Pathways Ltd."
  - name: "Gregg Walker"
    affiliation: "Parks Canada"
editor: visual
nocite: '@*'
bibliography: references.bib
toc: true
toc-depth: 3
toc-expand: true
prefer-html: true
toc-location: left
styles: styles.css
github: https://github.com/biodiversitypathways/pc-prescribed-fire
---

This is a test

```{r}

library(wildrtrax)
library(tidyverse)
library(sf)
library(ggrepel)
library(leaflet)
library(vegan)

load("pc-fire.RData")
#save.image("pc-fire.RData")

wt_auth()
```

```{r, eval = F, include = T}
# Download data

burn_projects <- c(2291, 282, 662, 672, 1092, 2021, 2878, 3577, 388, 1251, 1252, 1253, 1935, 2879, 2195, 2317, 2286, 2300, 2640, 2282, 3127, 4091)

pf_fire_locs <- read_csv("pf-fire-locations.csv") |>
  mutate(year = year(parse_date_time(recording_date_time, orders = c("mdy HM")))) |>
  select(-recording_date_time) |>
  distinct() |>
  filter(!location_id == 489836) 

burns <- wt_get_projects("ARU") |>
  filter(project_id %in% burn_projects) |>
  pull(project_id) |>
  wt_download_report('ARU', 'main') |>
  bind_rows() |>
  mutate(year = year(recording_date_time))

parks <- read_sf("./assets/National_Parks_and_National_Park_Reserves_of_Canada_Legislative_Boundaries.shp") |>
  st_transform(4326) |>
  st_make_valid()

parks_fire <- st_join(burn_sf, parks, join = st_intersects) |>
  dplyr::filter(!is.na(adminAreaI)) |>
  st_drop_geometry() |>
  select(adminAreaN) |>
  distinct() |>
  pull()

parks <- parks |> filter(adminAreaN %in% parks_fire)

```

# Introduction



# Methods

```{r}
# Wrangle

burn_locs <- burns |>
  select(location, location_id, latitude, longitude) |>
  distinct() |>
  filter(!is.na(latitude))

burn_sf <- st_as_sf(burn_locs, coords = c("longitude","latitude"), crs = 4326)

burn_locs |>
  filter(!is.na(latitude)) |>
  left_join(burns |> select(project_id, location_id) |> distinct(), by = "location_id") |>
  left_join(wt_get_projects("ARU") |> select(project_id, organization_name) |> distinct(), by = "project_id") |>
  select(organization_name, location) |>
  distinct()

burns_fire <- burns |>
  left_join(pf_fire_locs, by = c("location_id","year"))

```

```{r}
# Map

leaflet() %>%
  addTiles() %>%
  addPolygons(
    data = parks,
    popup = ~adminAreaN,
    fillOpacity = 0.4,
    color = "green"
  ) %>%
  addCircleMarkers(
    data = burn_locs,
    lng = ~longitude,
    lat = ~latitude,
    popup = ~paste("Location:", location),
    fillOpacity = 1,
    color = "black",
    radius = 6
  ) %>%
  addMeasure(primaryLengthUnit = "meters",
             primaryAreaUnit = "sqmeters") %>%
  addMiniMap(position = "bottomleft")

```

```{r}
# Covariates

covs <- burns_fire |>
  left_join(wt_get_projects("ARU") |> select(organization_name, project, project_id), by = "project_id") |>
  select(organization_name, project, project_id, location, location_id, year, sample_type, freq_burned, yrs_since_fire, pf_severity, veg_type) |>
  distinct()

covs |>
  count(organization_name, project, project_id, year)
covs |>
  count(veg_type)
covs |>
  count(location, year) |> 
  filter(n>1)

```

```{r}

c_p <- covs |>
  filter(!is.na(sample_type)) |>
  group_by(location_id) |>
  filter(all(c("pre-burn", "post-burn") %in% sample_type)) |>
  ungroup() |>
  select(location_id) |>
  distinct() |>
  pull()

prepost <- burns_fire |>
  filter(location_id %in% c_p) |>
  group_by(organization, location, location_id, year, sample_type) |>
  summarise(
    richness = n_distinct(species_code),
    .groups = "drop"
  ) %>%
  group_by(organization, location, location_id, sample_type) %>%
  summarise(mean_richness = mean(richness), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = sample_type, values_from = mean_richness)

wilcox.test(prepost$`pre-burn`,
            prepost$`post-burn`,
            paired = TRUE)

prepost %>%
  select(organization, location, location_id, `pre-burn`, `post-burn`) %>%
  pivot_longer(
    cols = c(`pre-burn`, `post-burn`),
    names_to = "sample_type",
    values_to = "value"
  ) |>
  mutate(
    sample_type = factor(sample_type,
                         levels = c("pre-burn", "post-burn"))
  ) |>
  ggplot(aes(x = sample_type, y = value, group = location_id, colour = organization)) +
  geom_line(alpha = 0.4) +
  geom_point(size = 2) +
  stat_summary(
    fun = median,
    geom = "point",
    size = 4
  ) +
  labs(
    x = NULL,
    y = "Species richness",
    title = "Paired pre- and post-burn comparison"
  ) +
  theme_bw()

```


```{r}

comm_long <- burns_fire %>%
  filter(location_id %in% c_p) %>%
  filter(sample_type %in% c("pre-burn", "post-burn")) %>%
  group_by(location_id, year, sample_type, veg_type, species_code) %>%
  summarise(abundance = n(), .groups = "drop")

comm_mat <- comm_long %>%
  unite(site_id, location_id, year, sample_type, remove = FALSE) %>%
  pivot_wider(
    names_from = species_code,
    values_from = abundance,
    values_fill = 0)

multi_type <- comm_mat  %>%
  dplyr::select(site_id, location_id, year, sample_type, veg_type) %>%
  distinct() %>%
  drop_na()

t3 <- rda(comm_mat[,-c(1:5)] ~ sample_type + veg_type, data = multi_type)
t3scores <- scores(t3, display = "sites") %>%
as.data.frame() %>%
rownames_to_column("site") %>%
bind_cols(., multi_type)
t3vect <- scores(t3, display = "species") %>%
as.data.frame()

plot_RDA <- ggplot(data = t3scores, aes(x = RDA1, y = RDA2)) +
  geom_point(data = t3scores, aes(x = RDA1, y = RDA2, colour = veg_type), 
             alpha = 0.7, size = 3, shape = 16) +
  stat_ellipse(data = t3scores, aes(colour = sample_type), 
               linetype = 1, type = 'norm', level = 0.67, size = 1) +
  geom_vline(xintercept = 0, color = "#A19E99", linetype = 2, size = 1) +
  geom_hline(yintercept = 0, color = "#A19E99", linetype = 2, size = 1) +
  geom_segment(data = t3vect, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
               arrow = arrow(length = unit(0.2, "cm")), size = 0.3) +
  geom_text_repel(data = t3vect, aes(x = RDA1, y = RDA2, label = rownames(t3vect)), 
                  size = 3, colour = "black", fontface = "italic", 
                  max.overlaps = 10, 
                  segment.color = "grey70") +
  theme_bw() +
  scale_colour_viridis_d(option = "cividis", end = 0.9) +
  labs(x = "RDA1", y = "RDA2", title = "Species-fire associations", 
       colour = "Sample Type") +
  theme(legend.position = "right", 
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 9), 
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))

plot_RDA

```


# Results

```{r}

shannon_d <- burns_fire |> 
  wt_tidy_species(remove = c("mammal","amphibian","abiotic","insect","unknown"), zerofill = F) |>
  inner_join(wt_get_species() |> dplyr::select(species_code, species_class, species_order), by = "species_code") |>
  dplyr::select(location, location_id, recording_date_time, species_code, species_common_name, individual_order, abundance) |>
  distinct() |>
  group_by(location, location_id, recording_date_time, species_code, species_common_name) |>
  summarise(count = max(individual_order)) |>
  ungroup() |>
  pivot_wider(names_from = species_code, values_from = count, values_fill = 0) |>
  pivot_longer(cols = -(location:species_common_name), names_to = "species", values_to = "count") |>
  group_by(location, location_id, year = year(recording_date_time), species) |>
  summarise(total_count = sum(count)) |>
  ungroup() |>
  group_by(location, location_id, year) |>
  summarise(shannon_index = diversity(total_count, index = "shannon")) |>
  ungroup() |>
  left_join(covs |> select(location_id:veg_type), by = c("location_id","year"))
  

shannon_d |>
  filter(!is.na(shannon_index), !is.na(veg_type)) |>
  ggplot(aes(x = factor(year), y = shannon_index, fill = factor(year))) +
  geom_boxplot() +
  geom_point(alpha = 0.6, colour = "grey") +
  labs(x = "Year",
       y = "Shannon diversity index per location") +
  theme_bw() +
  guides(fill = guide_legend(title = "Year")) +
  scale_fill_viridis_d(alpha = 0.8, option = "cividis") +
  facet_wrap(~ veg_type)

```
```{r}

shannon_d |>
  filter(!is.na(shannon_index), !is.na(sample_type), !is.na(veg_type)) |>
  mutate(sample_type = factor(sample_type, levels = c("pre-burn", "post-burn"))) |>
  ggplot(aes(x = sample_type, y = shannon_index, fill = sample_type)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8) +
  geom_jitter(width = 0.2, alpha = 0.6, color = "grey40") +
  facet_wrap(~ veg_type, scales = "free_y") +
  scale_fill_viridis_d(option = "cividis", end = 0.8) +
  labs(
    x = "Burn Status",
    y = "Shannon Diversity Index",
    fill = "Sample Type",
    title = "Shannon Diversity Pre- and Post-Burn by Vegetation Type"
  ) +
  theme_bw(base_size = 14) +
  theme(
    legend.position = "bottom"
  )

```

# Discussion and Recommendations
